# Generated by Django 5.2.6 on 2025-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_retrained', models.DateTimeField(auto_now=True)),
                ('tfidf_matrix', models.BinaryField()),
                ('cosine_sim', models.BinaryField()),
            ],
        ),
    ]
